apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: eksclusters.compute.aws.crossplane.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.state
    name: STATUS
    type: string
  - JSONPath: .status.clusterName
    name: CLUSTER-NAME
    type: string
  - JSONPath: .status.endpoint
    name: ENDPOINT
    type: string
  - JSONPath: .spec.classRef.name
    name: CLUSTER-CLASS
    type: string
  - JSONPath: .spec.location
    name: LOCATION
    type: string
  - JSONPath: .spec.reclaimPolicy
    name: RECLAIM-POLICY
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: compute.aws.crossplane.io
  names:
    kind: EKSCluster
    plural: eksclusters
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            claimRef:
              type: object
            classRef:
              type: object
            cliInput:
              type: string
            clientRequestToken:
              type: string
            clusterVersion:
              enum:
              - "1.10"
              - "1.11"
              type: string
            connectionSecretNameOverride:
              type: string
            generateCLISkeleton:
              type: string
            mapRoles:
              items:
                properties:
                  groups:
                    items:
                      type: string
                    type: array
                  rolearn:
                    type: string
                  username:
                    type: string
                required:
                - rolearn
                - username
                - groups
                type: object
              type: array
            mapUsers:
              items:
                properties:
                  groups:
                    items:
                      type: string
                    type: array
                  userarn:
                    type: string
                  username:
                    type: string
                required:
                - userarn
                - username
                - groups
                type: object
              type: array
            nodePools:
              items:
                type: object
              type: array
            providerRef:
              type: object
            reclaimPolicy:
              type: string
            region:
              type: string
            roleARN:
              type: string
            securityGroupIds:
              items:
                type: string
              type: array
            subnetIds:
              items:
                type: string
              type: array
            vpcId:
              type: string
          required:
          - region
          - roleARN
          - vpcId
          - subnetIds
          - securityGroupIds
          - nodePools
          - providerRef
          type: object
        status:
          properties:
            attachedNodePools:
              type: object
            connectionSecretRef:
              type: object
            endpoint:
              type: string
            resourceName:
              type: string
            state:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
